---
:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30
:queues:
  - default
  - [low_priority, 1]
  # - [high_priority, 2]
:schedule:
  ExpensesCleanupJob:
    cron: '*/5 * * * *'
    queue: low_priority
    enabled: true
  NopJob:
    cron: '*/10 * * * *'
    queue: low_priority
    enabled: true
  SummaryEmailJob:
    cron: <%= ENV.fetch("SUMMARY_EMAIL_CRON_STRING") %>
    queue: low_priority
    enabled: true
  SendBackupEmailJob:
    cron: <%= ENV.fetch("BACKUP_EMAIL_CRON_STRING") %>
    queue: low_priority
    enabled: true
  BackupToDiskJob:
    cron: <%= ENV.fetch("BACKUP_TO_DISK_CRON_STRING") %>
    queue: low_priority
    enabled: true
    args: <%= ENV.fetch("BACKUP_OUTPUT_FILE") %>
